/*
===============================================================================
Project : Olist E-commerce Sales Analytics
File    : 09_advanced_seller_analysis.sql

Purpose:
Advanced seller performance analysis using CTEs and Window Functions.

Business Questions:
1. What is the total revenue generated by each seller?
2. How many orders did each seller receive?
3. What is the average order value for each seller?
4. What is each seller's revenue rank?
5. Who are the top-performing sellers?

Author : Devi Sri Parvathi Junjuri
===============================================================================
*/


-- ============================================================================
-- 1. Seller Performance
-- ============================================================================

WITH seller_performance AS (
    SELECT
        oi.seller_id,

        COUNT(DISTINCT oi.order_id) AS total_orders,

        SUM(oi.price) AS total_revenue

    FROM raw.order_items oi

    GROUP BY oi.seller_id
)

SELECT
    seller_id,
    total_orders,
    ROUND(total_revenue, 2) AS total_revenue,

    ROUND(
        total_revenue / NULLIF(total_orders, 0),
        2
    ) AS average_order_value

FROM seller_performance

ORDER BY total_revenue DESC;


-- ============================================================================
-- 2. Seller Revenue Ranking
-- ============================================================================

WITH seller_performance AS (
    SELECT
        oi.seller_id,
        COUNT(DISTINCT oi.order_id) AS total_orders,
        SUM(oi.price) AS total_revenue
    FROM raw.order_items oi
    GROUP BY oi.seller_id
),

ranked_sellers AS (
    SELECT
        seller_id,
        total_orders,
        total_revenue,

        RANK() OVER (
            ORDER BY total_revenue DESC
        ) AS revenue_rank

    FROM seller_performance
)

SELECT
    seller_id,
    total_orders,
    ROUND(total_revenue, 2) AS total_revenue,
    revenue_rank
FROM ranked_sellers
ORDER BY revenue_rank;


-- ============================================================================
-- 3. Top 10 Sellers by Revenue
-- ============================================================================

WITH seller_performance AS (
    SELECT
        oi.seller_id,
        COUNT(DISTINCT oi.order_id) AS total_orders,
        SUM(oi.price) AS total_revenue
    FROM raw.order_items oi
    GROUP BY oi.seller_id
),

ranked_sellers AS (
    SELECT
        seller_id,
        total_orders,
        total_revenue,

        RANK() OVER (
            ORDER BY total_revenue DESC
        ) AS revenue_rank

    FROM seller_performance
)

SELECT
    seller_id,
    total_orders,
    ROUND(total_revenue, 2) AS total_revenue,
    revenue_rank
FROM ranked_sellers
WHERE revenue_rank <= 10
ORDER BY revenue_rank;


-- ============================================================================
-- 4. Seller Revenue Contribution
-- ============================================================================

WITH seller_performance AS (
    SELECT
        oi.seller_id,
        SUM(oi.price) AS total_revenue
    FROM raw.order_items oi
    GROUP BY oi.seller_id
)

SELECT
    seller_id,
    ROUND(total_revenue, 2) AS total_revenue,

    ROUND(
        total_revenue * 100.0 /
        SUM(total_revenue) OVER (),
        2
    ) AS revenue_percentage

FROM seller_performance

ORDER BY total_revenue DESC;


-- ============================================================================
-- 5. Top 10% Sellers by Revenue
-- ============================================================================

WITH seller_performance AS (
    SELECT
        oi.seller_id,
        SUM(oi.price) AS total_revenue
    FROM raw.order_items oi
    GROUP BY oi.seller_id
),

seller_deciles AS (
    SELECT
        seller_id,
        total_revenue,

        NTILE(10) OVER (
            ORDER BY total_revenue DESC
        ) AS revenue_decile

    FROM seller_performance
)

SELECT
    seller_id,
    ROUND(total_revenue, 2) AS total_revenue,
    revenue_decile

FROM seller_deciles

WHERE revenue_decile = 1

ORDER BY total_revenue DESC;